[package]
name = "hello_move"
version = "1.0.0"
edition = "2024.beta"
license = "MIT"
authors = ["CYBWithFlourish(project.samclak@gmail.com)"]

[dependencies]
Sui = { local = "/home/samcl/.sui/sui/crates/sui-framework/packages/sui-framework" }
MoveStdlib = { local = "/home/samcl/.sui/sui/crates/sui-framework/packages/move-stdlib" }
SuiSystem = { local = "/home/samcl/.sui/sui/crates/sui-framework/packages/sui-system" }
Bridge = { local = "/home/samcl/.sui/sui/crates/sui-framework/packages/bridge" }

[addresses]
hello_move = "0x0"